name: Ruby CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby-version: [2.5, 2.6, 2.7]
        rails-version: [5.2.x, 6.1.x]
    env:
      RAILS_VERSION: ${{ matrix.rails-version }}
      CONFIG_FILE: bizside_test_app/config/bizside.yml

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Install gem
        run: bundle exec rake install
      - name: Set up test app
        run: bundle install -j4
        working-directory: ./bizside_test_app
      - name: Set environment variables
        run: echo >> "CONFIG_FILE=bizside_test_app/config/bizside_rails6.yml" >> $GITHUB_ENV
        if: ${{ matrix.rails-version == '6.1.x' }}
      - name: Run tests
        run: rails test
        working-directory: ./bizside_test_app
